---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: selenium
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          labels:
            egress.home.arpa/internet: allow
            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
            ingress.home.arpa/nginx-internal: allow
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: selenium/standalone-chrome
              tag: "126.0"
            env:
              SE_NODE_SESSION_TIMEOUT: "300"
              SE_START_XVFB: false
              SE_START_VNC: false
            resources:
              requests:
                cpu: 14m
                memory: 431M
              limits:
                memory: 431M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

    service:
      main:
        ports:
          http:
            port: 4444

    ingress:
      main:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      tmp:
        type: emptyDir
