---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: Paperless
        property: username
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: Paperless
        property: password
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: paperless
        property: secret key
    - secretKey: PAPERLESS_OCR_LANGUAGE
      remoteRef:
        key: paperless
        property: ocr langs
