---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Deploy key
        GH_DEPLOY_KEY: "{{ .hass_gh_deploy_key }}"

        # Home-Assistant
        SECRET_INTERNAL_URL: http://10.1.3.151:8123
        SECRET_INTERNAL_URL_DIRECT: http://10.1.3.151:8123
        SECRET_EXTERNAL_URL: https://${HOSTNAME}
        SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16

        # Home-Assistant Zones
        SECRET_ZONE_HOME_HOUSE_NUMBER: "{{ .hass_house_number }}"
        SECRET_ZONE_HOME_POSTAL_CODE: "{{ .hass_postal_code }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .hass_elevation }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .hass_latitude }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .hass_longitude }}"
  dataFrom:
    - extract:
        key: home-assistant
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "hass_$1"
