---
# Area
area/ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**/*"
# Cluster
cluster/qsb:
  - changed-files:
      - any-glob-to-any-file: kubernetes/qsb/**/*
cluster/asc:
  - changed-files:
      - any-glob-to-any-file: kubernetes/asc/**/*
