---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sccarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sccarr-secret
    creationPolicy: Owner
  data:
    - secretKey: aria2_rpc_secret
      remoteRef:
        key: Aria2
        property: rpc secret
    - secretKey: scc_token
      remoteRef:
        key: SCC
        property: token
    - secretKey: scc_website
      remoteRef:
        key: SCC
        property: url
    - secretKey: sonarr_api_key
      remoteRef:
        key: Sonarr
        property: api key
    - secretKey: radarr_api_key
      remoteRef:
        key: Radarr
        property: api key
    - secretKey: ws_password
      remoteRef:
        key: Webshare
        property: password
    - secretKey: ws_username
      remoteRef:
        key: Webshare
        property: username
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-vpn
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-vpn-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        key: Privado VPN
        property: endpoint ip
    - secretKey: WIREGUARD_ENDPOINT_PORT
      remoteRef:
        key: Privado VPN
        property: endpoint port
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: Privado VPN
        property: public key
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Privado VPN
        property: private key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Privado VPN
        property: address
