---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sccarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      sccarr:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          schedule: 5 * * * *

        pod:
          imagePullSecrets:
            - name: private-ghcr
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [65542]

        initContainers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.39.0
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: sccarr-vpn-secret
            restartPolicy: Always
            securityContext:
              capabilities:
                add: [NET_ADMIN]
              allowPrivilegeEscalation: false

        containers:
          app:
            image:
              repository: ghcr.io/aka-raccoon/sccarr
              tag: 0.0.5@sha256:51aae95ccafade86feb2c9b152e9e6167a050d0870b5cca611f900915d236dad
            env:
              ARIA2_URL: http://aria2.downloads.svc.cluster.local
              ARIA2_PORT: 8080
              ARIA2_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: aria2_rpc_secret
              SONARR_URL: http://sonarr.downloads.svc.cluster.local:8989
              SONARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: sonarr_api_key
              SONARR_QUALITY_PROFILE: HD-1080p - Czech
              RADARR_URL: http://radarr.downloads.svc.cluster.local:7878
              RADARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: radarr_api_key
              RADARR_QUALITY_PROFILE: HD-1080p - Czech
              WS_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: ws_username
              WS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: ws_password
              SCC_URL:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: scc_website
              SCC_ACCESS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: sccarr-secret
                    key: scc_token
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              capabilities:
                drop: [ALL]
