---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname pinchflat
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/qsb/apps/media/pinchflat/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: pinchflat.${DOMAIN}
      APP_UID: "568"
      APP_GID: "568"
      VOLSYNC_CLAIM: pinchflat-config
