---
ingress:
  - hostname: '${DOMAIN}'
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.${DOMAIN}
  - hostname: '*.${DOMAIN}'
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.${DOMAIN}
  - service: http_status:404
