---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-safe-settings
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gh-safe-settings-secret
    creationPolicy: Owner
  data:
    - secretKey: app-id
      remoteRef:
        key: "GH Safe Settings"
        property: "app id"
    - secretKey: private-key
      remoteRef:
        key: "GH Safe Settings"
        property: "private key"
    - secretKey: webhook-secret
      remoteRef:
        key: "GH Safe Settings"
        property: "webhook secret"
