---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kube-prometheus-stack-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: thanos
            endpoint: s3.${DOMAIN}
            access_key: {{ .s3_access_key }}
            secret_key: {{ .s3_secret_key }}
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: Thanos
        property: s3 access key
    - secretKey: s3_secret_key
      remoteRef:
        key: Thanos
        property: s3 secret key
