---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: miniflux-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_USERNAME: "{{ .miniflux_username }}"
        ADMIN_PASSWORD: "{{ .miniflux_password }}"
        OAUTH2_CLIENT_ID: "{{ .miniflux_client_id }}"
        OAUTH2_CLIENT_SECRET: "{{ .miniflux_client_secret }}"
  dataFrom:
    - extract:
        key: Miniflux
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "miniflux_$1"
