---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-r2"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "${APP}-volsync-r2"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ .r2_url }}/${APP}"
        RESTIC_PASSWORD: "{{ .restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ .r2_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .r2_secret_key }}"
  data:
    - secretKey: r2_access_key
      remoteRef:
        key: Volsync R2 bucket
        property: s3 access key
    - secretKey: r2_secret_key
      remoteRef:
        key: Volsync R2 bucket
        property: s3 secret key
    - secretKey: r2_url
      remoteRef:
        key: Volsync R2 bucket
        property: url
    - secretKey: restic_password
      remoteRef:
        key: Volsync R2 bucket
        property: restic password
