---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matchbox
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: quay.io/poseidon/matchbox
              tag: v0.11.0
            args:
              - address=0.0.0.0:80
            resources:
              requests:
                cpu: 5m
                memory: 128M
            securityContext:
              capabilities:
                add: [NET_BIND_SERVICE]
              runAsUser: 568

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: &host "matchbox.${DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http

    persistence:
      dev:
        type: hostPath
        hostPath: /tank/apps/matchbox
        hostPathType: Directory
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/lib/matchbox
            readOnly: false
