---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: pgo-s3-creds
spec:
  externalSecretName: pgo-s3-creds

  namespaceSelector:
    matchLabels:
      pgo-enabled-${DOMAIN}: "true"

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect

    target:
      name: pgo-s3-creds
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          s3.conf: |
            [global]
            repo1-s3-key={{ .s3_access_key }}
            repo1-s3-key-secret={{ .s3_secret_key }}
    data:
      - secretKey: s3_access_key
        remoteRef:
          key: Crunchy Postgres
          property: s3 access key
      - secretKey: s3_secret_key
        remoteRef:
          key: Crunchy Postgres
          property: s3 secret key
