---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: private-ghcr
spec:
  externalSecretName: private-ghcr
  namespaceSelector:
    matchLabels:
      private-ghcr: 'true'
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: '{"auths": {"ghcr.io": {"auth": "{{ .token }}"}}}'
      name: ghcr-secret
      creationPolicy: Owner
    data:
      - secretKey: token
        remoteRef:
          key: GHCR
          property: token
