---
clusterName: ${CLUSTER_NAME}
endpoint: 'https://${CLUSTER_VIP}:6443'

talosVersion: v1.5.5
kubernetesVersion: 1.28.4

# Image URL rendered on https://factory.talos.dev
talosImageURL: factory.talos.dev/installer/22b1d04da881ef7c57edb0f24d1f3ba2c78a8e22cbe3fa9af4f42d487b2863f7

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${CLUSTER_VIP}

additionalMachineCertSans:
  - ${CLUSTER_VIP}
  - ${CLUSTER_NAME}.${DOMAIN}

nodes:
  - hostname: delta.${CLUSTER_NAME}.${DOMAIN}
    ipAddress: 192.168.10.10
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata3/host2/target2:0:0/2:0:0:0/
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: '1c:69:7a:a6:d3:f2'
        dhcp: true
        vip:
          ip: ${CLUSTER_VIP}

  - hostname: enigma.${CLUSTER_NAME}.${DOMAIN}
    ipAddress: 192.168.10.11
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 'd8:9e:f3:84:82:e7'
        dhcp: true
        vip:
          ip: ${CLUSTER_VIP}

  - hostname: omega.${CLUSTER_NAME}.${DOMAIN}
    ipAddress: 192.168.10.12
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 'b8:85:84:9f:dc:1e'
        dhcp: true
        vip:
          ip: ${CLUSTER_VIP}

controlPlane:
  patches:
    # Disable search DOMAIN everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true

    # Force nameserver
    - |-
      machine:
        network:
          nameservers:
            - 192.168.10.1

    # Configure NTP
    - |-
      machine:
        time:
          disabled: false
          servers:
            - 192.168.10.1

    # Enable KubePrism
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    # Configure cluster loopback
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: ${CLUSTER_VIP}
              aliases:
                - ${CLUSTER_NAME}.${DOMAIN}

    # Configure pull through cache
    # - |-
    #   machine:
    #     registries:
    #       mirrors:
    #         docker.io:
    #           endpoints:
    #             - https://zot.${DOMAIN}/v2/docker.io
    #           overridePath: true
    #         ghcr.io:
    #           endpoints:
    #             - https://zot.${DOMAIN}/v2/ghcr.io
    #           overridePath: true
    #         quay.io:
    #           endpoints:
    #             - https://zot.${DOMAIN}/v2/quay.io
    #           overridePath: true
    #         gcr.io:
    #           endpoints:
    #             - https://zot.${DOMAIN}/v2/gcr.io
    #           overridePath: true
    #         registry.k8s.io:
    #           endpoints:
    #             - https://zot.${DOMAIN}/v2/registry.k8s.io
    #           overridePath: true
    #         public.ecr.aws:
    #           endpoints:
    #             - https://zot.${DOMAIN}/v2/public.ecr.aws
    #           overridePath: true

    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        proxy:
          disabled: true

    # ETCD configuration
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.10.0/24

    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true

    # Configure nfs mount options
    - |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nodiratime=True
              rsize=131072
              wsize=131072
              nconnect=8

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Kubelet configuration
    - |-
      machine:
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 192.168.10.0/24

    # Custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
