---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radicale
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radicale-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users: |-
          {{ .a_user }}:{{ .a_password }}
          {{ .e_user }}:{{ .e_password }}
          {{ .o_user }}:{{ .o_password }}
          {{ .p_user }}:{{ .p_password }}
  data:
    - secretKey: a_user
      remoteRef:
        key: Radicale (a)
        property: username
    - secretKey: a_password
      remoteRef:
        key: Radicale (a)
        property: password
    - secretKey: e_user
      remoteRef:
        key: Radicale (e)
        property: username
    - secretKey: e_password
      remoteRef:
        key: Radicale (e)
        property: password
    - secretKey: o_user
      remoteRef:
        key: Radicale (o)
        property: username
    - secretKey: o_password
      remoteRef:
        key: Radicale (o)
        property: password
    - secretKey: p_user
      remoteRef:
        key: Radicale (p)
        property: username
    - secretKey: p_password
      remoteRef:
        key: Radicale (p)
        property: password
