---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "${APP}-volsync-minio"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .s3_url }}/${APP}"
        RESTIC_PASSWORD: "{{ .restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ .s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3_secret_key }}"
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: Volsync
        property: s3 access key
    - secretKey: s3_secret_key
      remoteRef:
        key: Volsync
        property: s3 secret key
    - secretKey: s3_url
      remoteRef:
        key: Volsync
        property: s3 url
    - secretKey: restic_password
      remoteRef:
        key: Volsync
        property: restic password
