apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-secrets
  namespace: flux-system
data:
  ACME_EMAIL: ENC[AES256_GCM,data:4vcDZ3zWs4CqdPgOv8xrqpY5TdMTQahV/ZI=,iv:xX9vY80xGM0U8sH1fKRnNIJZ5aMaXLCRsIs4HPWJcB8=,tag:DvBHcILZuhZQFWanU+ogVg==,type:str]
  DOMAIN: ENC[AES256_GCM,data:XpCtw1atq+6YLENH8WycJ6vQ,iv:8vTV7ApIW1EJu4Cw3I57hRw/Hm6dxB6GIk39hhug0Ko=,tag:tD4k+LjxD0SMdxQPMkZcMw==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:sWnKX3ikxDNR2els9Q==,iv:bdoaZyZS1ezsOdz5EgCEKcRF+lqEvd2/p8CXB8NiqpA=,tag:bf1bA1DfK6TWR4DNgzSphQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qr30xfa47s84mcdcsp0h69x7ryflckmc20reyezc9wfysleeydvqc2v2y3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSFNVdEtXNnlJOUplbUNy
        UG9zVEVhYzNFY0RwYWtFUitEKzI3c1IyTVY0Cm54MmFXR2Y5MngvdmlkbytkajRt
        OGNtQkJRMGtFaDRQbWZTN1l0cXFtSEEKLS0tIDZ0WG1qSkdJdlJTWnBjS29LeEVR
        NEtvRlppOE8wYmhmUzBxRytueDlZV28KwBVes2MH6BbNL63Gv7G/UjG7gzx82Kp9
        Lm8b4VAlqUi1QLahf6gAs53H3uqrRWNyRFdQTbPcGQm+HqnNsACtrw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vx9xymjgckm2rvzmkdpd6lm2dchm2lytcfguc0de82flmv8323hsgdw9pv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTnpCbytnVUxrMUpESXVM
        enJhcUk1UnBaUW9EREpneFlWS0VORDV1VDBRCjdHV3BSZXR5QTZQTEVTcmwremlC
        dzBGRGhZRWU1aWFuS0NkQUl0LzkyaUkKLS0tIExGN0Vncm00RVV3VTJhQUZlODJB
        cStBR2MvZTdHZ3JBRU01WEs0ZHNIejgKF+RyNvsG2+0c7NFUZmNXlT8w2HcHwNoz
        f8fH7zqX57qr5xkFbW+UX7RRSqgvnePvNuTi9rdnxV8VbgPv6sLy/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-12-11T17:47:25Z'
  mac: ENC[AES256_GCM,data:oxK4HvnHtPCnt29lYknw5lXP2hRRZ8VGZEXqkASox+9I7D1Gui16sqh9CHjeHnuuicN7YgUWo40JjzgHHrR8cnyRQ3hHAYx7CBrL19c6IfhtKiBEjOCC43Onty0zXqXhhX1ZuN/NUaHlQMJlv7czzSo2z8dxo6sX5f/0TGYVL0Q=,iv:3KyKGx0WHZtHVRHuj53zE30KNCm0WYyXQl3aEWJk9r4=,tag:Ux4gk3AMYK7lVNRN6BCmyw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.0
