---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-unifi
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-unifi-secret
    creationPolicy: Owner
  data:
    - secretKey: external_dns_password
      remoteRef:
        key: External DNS Unifi User
        property: password
    - secretKey: external_dns_user
      remoteRef:
        key: External DNS Unifi User
        property: username
