---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-controller-sops-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tf-controller-sops-key
    creationPolicy: Owner
  data:
    - secretKey: keys.txt
      remoteRef:
        key: Terraform Controller
        property: age key
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-controller-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tf-controller-secrets
    creationPolicy: Owner
  data:
    - secretKey: OP_CONNECT_TOKEN
      remoteRef:
        key: Terraform Controller
        property: 1password token
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tfe-cli-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tfe-cli-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        terraform.tfrc: |-
          credentials "app.terraform.io" {
            token = "{{ .tfcontroller_terraform_cloud_token }}"
          }
  dataFrom:
    - extract:
        key: Terraform Controller
      rewrite:
        - regexp:
            source: "(.*)"
            target: "tfcontroller_$1"
