apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
stringData:
  token: ENC[AES256_GCM,data:k3mF2mXHzlRMK+Mpn9BXP+kt468sYFZ5JyZLVG4jQEurAYqaCOmkkK1yaO0qfHGQlb5rkcg8H8VZER/ikQN3BDvW/d6h2M1QVJ4h4Iq0CMz2Cmaj/Qahfvc534QKNFvbr7vICQKih5g18K+X4KNFyg7ew8z2fyJlAJU7GEnJhq5EdWiGgqCCXG1rpB98GUXvAKqjrTNNcpIVyhUjjZ4po9CAGWO+8fR89lVYiS54CwKkMl6zvtyu/9J4X7KP5nJ8d3xTvIJ9yi+65Ig8ukzkeI/O8ug+Sdg1uSyzweKkTgN9roJhXUQeExVPO0FBCd73sOtBGuXjM4AaIytFRpTDiIJcLSOvJbJmsm8ZWaMoB1FMv6prqPUtnqt3I+gezkRkPBRW8oj89wub0V+oGg6grptfZdM9VfBIuXD6Rpf1aPhkHCPv+V+kBAL855cf3Z1vLNK7ILuHuTQla2aVmNjI7EM1uDoqmSZvL2dNQTXxr8NLGe35IOB70wilYamuIlN/WxQcU3fBbxAB6Ylwsgup32KlDkdZyXhNL0H3fvH5C5cjBUbVw8ynbqwKeYajsblIYxvwmuI6e3ydEZwN1gIXGY+VrLAR2vqHWmZH7Aq2B0DxAiD8+PqVlucdKhpf6WUjekNRhaSpDnLCcpwvSJzO4C8o+tpr7uwwLUoEOHr3tZi2zhPl9iBuM/Kc/YnvIlyckb4YIGUxneKQSs8uJ6NgUOi5XqIpSYtZT8uj0NbYSv62DgEAc8v4qHnRbZZDKkqqn4MGxd9pyp2Z4Dkaxzq0GmtiJl3nF9/GqVt/LtpTCVkdVHPPAaDditf/mX44jqvVpNgWmTeUFrhcan5jWK4zZO1F,iv:1Bm/s1RXnMuFAyUG/cz3yguZ9tBTYo/Zg3q4boFxFsM=,tag:YY1k59wpt3R+/1gg8SvQNA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qr30xfa47s84mcdcsp0h69x7ryflckmc20reyezc9wfysleeydvqc2v2y3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbWNlODNFYU9iK3RxN3VS
        SC91UktqWTluMW95ZVByZE9ScjlOZ1dZRGwwCkRKTlJYQXlqb3I0V1YvSEk3bmg3
        LzBXb0ZXU3pZY2N3Q3FSMGNhZW1ZU28KLS0tIDBPTDRORG1TSTBVWUdhU3pWekth
        NFI4QWVRUk1CSm5uRXVCUzdMbGNrNjQKatES6rjXlHpLF5nYF6VAq2t6SynTh9sT
        fmUwUP7CWg+Z2ctvNbuq7DNXELVc4F6n0q5tL0dArF+TFgNOQnPGxw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k2f79x0m9lcu7x2vyemph9m5rrgezfy3kgl0gz7zjwuuwrhnfy0slpn0d6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxS2FrbE8yaU5mU3I1UktW
        TGVvdkRkUGkrL29KV29tMDBlMTRqVlNPcG53CmxjZzZSYTc3NFZ2Zk5kTDY0ZXZu
        R1Zjc01ZblNlR2RKNGJPRUxSMTRUYVkKLS0tIHlrTW81K3lDNHRRdEtBYlQ1ZTJp
        WmJianBLTXN2Zmk5cmltMTdhUG9lRW8KwJHdGdnbwfdGago2kp1oo6buOSRvmC7w
        jz5wyuLf35aqInQqD8ShCZoF9yq13HBB5PFhWJYYXnbx3IWtjCJdAw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vx9xymjgckm2rvzmkdpd6lm2dchm2lytcfguc0de82flmv8323hsgdw9pv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OS9vTlBrMUtaNDg4WDVX
        NzhiNHpmb3lBWk9ZZlFucDBKeGRaK3dVc3drCkhuMkJJbUxMcEZ3S2tXZEVvZEhL
        M3p4LzZOVDJORVdsci8xc1RBNHE0SkEKLS0tIGFVRjJabVk1b3c5SFFBeWlheks1
        ZkYxdW5sU1V1eHNvU2FpellHK3JRcTAKATCpuUZjRzzHCCPE967cLB9G1UerX3AK
        XAx6yA8OsXxhDKSek4QsG8G6oEpbks0HCX4i5uZHEeQeHgsFb13oZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-04T08:13:58Z"
  mac: ENC[AES256_GCM,data:AF+StqpVs4IwR7t1MjjVqlTvSUyBIWWhjwMtByTGkpp3pnUobj0eASvHzVjLoQG7VcGfbIkfPhqgJICXaGCR32upZHFeqJIqhq6+jN9nFT0LUZEcFVtHyI4eYHfz6SrHZP6fFY32Ss0XZ/7Sjq5LFsaxteo5wq04Laz6f7M/hj8=,iv:pAT8lVLf/x6AX/Sv//gqyBXYR/rDVz8OaY5n+i29+60=,tag:GVOzP7nljslaS9r3mnBGBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
