---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./networkpolicy.yaml
  # Flux-Kustomizations
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./lidarr/ks.yaml
  - ./freyrarr/ks.yaml
  - ./aria2/ks.yaml
  - ./sccarr/ks.yaml
