---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET: thanos
        S3_HOST: s3.${DOMAIN}
        S3_ACCESS_KEY: "{{ .s3_access_key }}"
        S3_SECRET_KEY: "{{ .s3_secret_key }}"
        S3_REGION: us-east-1
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: Thanos
        property: s3 access key
    - secretKey: s3_secret_key
      remoteRef:
        key: Thanos
        property: s3 secret key
