---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aka-raccoon.yaml
  - ./aka-raccoon-nebular-grid.yaml
  - ./rbac.yaml
