---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [65542]

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/lidarr-develop
              tag: 2.5.1@sha256:9c99577d2fb39f6d12e5c87b661181d155d7bf47ae3627e4c48e71f9c349f557
            env:
              COMPlus_EnableDiagnostics: "0"
              LIDARR__INSTANCE_NAME: Lidarr
              LIDARR__PORT: &port 8686
              LIDARR__AUTHENTICATION_METHOD: External
              LIDARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              LIDARR__APPLICATION_URL: https://lidarr.${DOMAIN}
              LIDARR__LOG_LEVEL: info
              LIDARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lidarr-secret
                    key: api_key
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 20m
                memory: 384Mi
              limits:
                memory: 1536Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]

    service:
      app:
        controller: lidarr
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.1.1.140
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal-nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ingress-int.${DOMAIN}
        hosts:
          - host: lidarr.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        type: nfs
        server: asc.internal
        path: /tank/media
        globalMounts:
          - path: /data/nas-media
