---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
metrics:
  - name: qsb_cluster_node_count
    query: count(count by (node) (kube_node_status_condition{cluster="qsb",condition="Ready"}))

  - name: qsb_cluster_pod_count
    query: sum(kube_pod_status_phase{cluster="qsb", phase="Running"})

  - name: qsb_cluster_cpu_usage
    query: round(avg(instance:node_cpu_utilisation:rate5m{cluster="qsb"}) * 100, 0.1)
    suffix: "%"
    colors:
      - {color: "green", min: 0, max: 35}
      - {color: "orange", min: 36, max: 75}
      - {color: "red", min: 76, max: 9999}

  - name: qsb_cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes{cluster="qsb"} - node_memory_MemAvailable_bytes{cluster="qsb"}) / sum(node_memory_MemTotal_bytes{cluster="qsb"}) * 100, 0.1)
    suffix: "%"
    colors:
      - {color: green, min: 0, max: 35}
      - {color: orange, min: 36, max: 75}
      - {color: red, min: 76, max: 9999}

  - name: qsb_cluster_age_days
    query: round((time() - max(kube_node_created{cluster="qsb"}) ) / 86400)
    suffix: "d"
    colors:
      - {color: "green", min: 0, max: 180}
      - {color: "orange", min: 181, max: 360}
      - {color: "red", min: 361, max: 9999}

  - name: qsb_cluster_uptime_days
    query: round(avg(node_time_seconds{cluster="qsb"} - node_boot_time_seconds{cluster="qsb"}) / 86400)
    suffix: "d"
    colors:
      - {color: "green", min: 0, max: 180}
      - {color: "orange", min: 181, max: 360}
      - {color: "red", min: 361, max: 9999}
