---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN}"
spec:
  secretName: "${DOMAIN}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN}"
  dnsNames:
    - "${DOMAIN}"
    - "*.${DOMAIN}"
