---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freyrarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freyrarr-secret
    creationPolicy: Owner
  data:
    - secretKey: lidarr_api_key
      remoteRef:
        key: Lidarr
        property: api key
