---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freyrarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      freyrarr:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          schedule: "15 * * * *"

        pod:
          imagePullSecrets:
            - name: private-ghcr
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542 # gladius:external-services

        initContainers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.39.0
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: sabnzbd-vpn-secret
            restartPolicy: Always
            securityContext:
              capabilities:
                add: [NET_ADMIN]
              allowPrivilegeEscalation: false

        containers:
          app:
            image:
              repository: ghcr.io/aka-raccoon/freyrarr
              tag: 0.0.5@sha256:bd59fa017aeb7a6b5fddc76d2bf31fe129b600ef44c4fc9aac7ad266108883cd
            env:
              DATA_DIR: /data/nas-media/downloads/freyrarr
              LIDARR_URL: http://lidarr.downloads.svc.cluster.local
              LIDARR_PORT: 8686
              LIDARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: freyrarr-secret
                    key: lidarr_api_key
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 1024Mi
              limits:
                memory: 6144Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              capabilities:
                drop: [ALL]

    persistence:
      config:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /home/kah/.config
      media:
        type: nfs
        server: asc.internal
        path: /tank/media/downloads/freyrarr
        globalMounts:
          - path: /data/nas-media/downloads/freyrarr
