---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542

        containers:
          main:
            image:
              repository: "ghcr.io/goofball222/unifi"
              tag: "8.3.32"
            env:
              # RUNAS_UID0: "false"
              # PUID: "999"
              # PGID: "999"
              JVM_MAX_HEAP_SIZE: "1024M"

            resources:
              requests:
                cpu: 12m
                memory: 764Mi
              limits:
                memory: 789Mi
    service:
      main:
        ports:
          http:
            port: 8443
            protocol: TCP

    ingress:
      main:
        enabled: true
        className: "internal-nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi-cont.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        type: hostPath
        hostPath: /tank/apps/unifi
        hostPathType: Directory
        globalMounts:
          - path: /usr/lib/unifi/data
