---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        authentik_secret_key: "{{ .authentik_secret_key }}"
        authentik_email_host: "{{ .mailgun_hostname }}"
        authentik_email_username: "{{ .mailgun_username }}"
        authentik_email_password: "{{ .mailgun_password }}"
        authentik_email_from: "{{ .authentik_email }}"
  dataFrom:
    - extract:
        key: Authentik
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
    - extract:
        key: Mailgun
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mailgun_$1"
