---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: crunchy-postgres-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .minio_access_key }}
          repo1-s3-key-secret={{ .minio_secret_key }}
          repo2-s3-key={{ .r2_access_key }}
          repo2-s3-key-secret={{ .r2_secret_key }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .backup_encryption_cipher }}
          repo2-cipher-pass={{ .backup_encryption_cipher }}
  data:
    - secretKey: minio_access_key
      remoteRef:
        key: Crunchy Postgres Minio bucket
        property: access key id
    - secretKey: minio_secret_key
      remoteRef:
        key: Crunchy Postgres Minio bucket
        property: secret access key
    - secretKey: r2_access_key
      remoteRef:
        key: Crunchy Postgres R2 bucket
        property: access key id
    - secretKey: r2_secret_key
      remoteRef:
        key: Crunchy Postgres R2 bucket
        property: secret access key
    - secretKey: backup_encryption_cipher
      remoteRef:
        key: Crunchy Postgres
        property: backup encryption cipher
