---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LDAP_QUERY_BIND: "{{ .bind_dn }}"
        LDAP_QUERY_PASSWORD: "{{ .bind_dn_password }}"
  data:
    - secretKey: bind_dn
      remoteRef:
        key: Mealie
        property: bind dn
    - secretKey: bind_dn_password
      remoteRef:
        key: Mealie
        property: bind dn password
