---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actual-bank-synchronizer
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-bank-synchronizer-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: Actual
        property: password
    - secretKey: sync_id
      remoteRef:
        key: Actual
        property: sync id
