---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpoller-secret
    creationPolicy: Owner
  data:
    - secretKey: unifipoller_user
      remoteRef:
        key: Unpoller
        property: username
    - secretKey: unifipoller_password
      remoteRef:
        key: Unpoller
        property: password
