apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-secrets
  namespace: flux-system
data:
  ACME_EMAIL: ENC[AES256_GCM,data:EfuYDnTVLWuOiuUzKnZrpDPQmSgaynq0AMM=,iv:osK0wAgA2oOvSAQ8I18Q2WwZvSF+9UFRzunBIge8yr4=,tag:6hmNXPdnnGMKlAF1CkvSYg==,type:str]
  DOMAIN: ENC[AES256_GCM,data:df0G8dBcJrrbKeI5ROg2uwfQ,iv:d1XV5bpmpVPRwwmaFGQSUaw076Rf2mVBR9UmPnqHbF8=,tag:wzJ9zhJatpS3vq1sfdXtyg==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:F2I9/9QKjJG/UKytEQ==,iv:tj5B5wJCeQG+Vtf07qWNFDPBOwkPcnP8Rdp+Bl8lH+g=,tag:kxQ13TnA67wuYxhj96Y8/g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qr30xfa47s84mcdcsp0h69x7ryflckmc20reyezc9wfysleeydvqc2v2y3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d2FaV1pYZm1oWlNYMzNN
        eVJhK09mdjZKMlZuaTdGUllTNURzcUZhajBRCmw2dTdEM1owVUU5NDdpQktKeGww
        c29HN0V0OEMyUVBtMHRtdzhxRnVkRTAKLS0tIHQ2ZFZhM3pGVmJpVG5VY2Iwa1Y0
        bVBSV01pNnZhdmg2eXFiRVY5T3hPOVUKQHu1UEZzlt8BVL83FoUGPmS0ommLJ2RF
        irJMlqce7ph1CxC0zGfj+ui0ski6WpyPZqSDn15wqKBUG/nJ+wpHRg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k2f79x0m9lcu7x2vyemph9m5rrgezfy3kgl0gz7zjwuuwrhnfy0slpn0d6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OGgwZDluc2RiWkpsRGdu
        T3JNV1VHeHhRbFZWdktDSUVzaG5hcmJQdVhnClVSdzM4ejhzZk1CcWxjWjVTcUJY
        WFBDSVdtRkREb0h6VDJuQUs5K2x5OUkKLS0tIFd4OHZqeW9yMnpkMDJWVnJTNW9t
        MytRMmFJQzVzZEpoYWhnWE42bnFyeDAKv0NU5mv4MHHcfHjCQHDN04pNM/2U7wYC
        OghxE9wLZgKl+YK+uI9D91LKRayGcUUQVinqulHz+fBeA+XvlHCwbg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vx9xymjgckm2rvzmkdpd6lm2dchm2lytcfguc0de82flmv8323hsgdw9pv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdGlsaS9UWTBpY3Q1V1NI
        QW9zRFlSUWZGNzN2dGlLNjlIRU5BYjJxa2pNCkdEZDZzTFRVR2ExV2dubURTZmE4
        THg4R1VOWVlpRjlxYi9CSWRmS29UY0kKLS0tIHN2K1o3ajY1TmlSU0phYlQ1eDNF
        MHNTU202YUxycWo0ZFJYeWdrYkw5N1kKjiZrIp+nzaHcMq5EISL5Gao4ebVfbJwo
        T+k90f0AVZT4FnB3LNDqQFV6xFGSS2W/9uV89MCWdtzRns5685imfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-04T08:13:57Z"
  mac: ENC[AES256_GCM,data:97WwXHm3KzWKlryOLWXTDaNhz6TAYHe1HJhyc3k1UmAwjsdP1NZTmIClwg3xoqduyYtrlx5VbjUbbpw/UEihOemqm8Yx/G6nRmBtrv4JNyhcqTKbJsKVTDLoqY/sQzSDmwgCnJ0eZdOcRvuOgIqonQxoAF2hhsRY2Sa9nKo0KOA=,iv:8PCKcTPfVFmns6Zgcgn1g2K2clQCez+WGkwEO6aySJ8=,tag:hQd8mULY0ZJdsLCIuis/CQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
